### PR TITLE
Added var, checks, comments and removed dependencies from the pi user

### PR DESCRIPTION
**Pull request by davidone**
1. There is no 'Press ENTER to begin', just a sleep so I removed the related echo
2. Will exit if the user isn't root (or if he's not using sudo)
3. Created some vars for users, paths
4. Fixed a couple of hardcoded things
5. Removed python3-rpi.gpio to prevent python3 to be installed.

### CODE REVIEW

**Comment by DexterInd** [comment]
Hey @davidone thank you for the pull request!  You've clearly made some awesome improvements to the script, thanks so much!!

Can I ask why you removed the python 3 dependencies?  Are they a problem?

**Comment by DexterInd** [comment]
@karan259 can you take a look at this as well?

**Comment by karan259** [comment]
@davidone : I was lookign at the change here: https://github.com/davidone/GrovePi/blob/master/Script/install.sh#L157 . Where is **${USER_PATH}** defined and do we really need to change it.

**Comment by davidone** [comment]
@karan259 my bad. It should be ${DIR_PATH}.

**Comment by davidone** [comment]
@DexterInd regarding python3, I installed raspbian jessie for my RPI 3 days ago and the 'default' python installed is 2.7.x so I think that installing the entire python3 stack is useless (my 2 cents).

**Comment by DexterInd** [comment]
@davidone , are you ok if we leave the Python3 dependencies in there?  the Pi Foundation has been pushing Python 3.  We still prefer p2.x, but the way the world is going, we'll need those installed.

**Comment by davidone** [comment]
@DexterInd sure, it was just a suggestion to save some disk space.

**Comment by davidone** [comment]
With the last commit I reintroduced the install of python3 packages, explained why on jessie getrboard/setup.sh will fail (no inittab due to systemd) with an external link on how to fix this.
Moreover added checks to do not write in /boot/config.txt if dtparam={i2c1,i2c}=on is already present.
Minor fixes.

**Comment by DexterInd** [comment]
Thanks @davidone , very nice work!

**Pull request merged**
