### PR TITLE
Troubleshooting didn't always detect GrovePi

### PR DESCRIPTION
**Pull request by CleoQc**
The troubleshooting script didn't always detect the GrovePi when it ran i2cdetect. It needed a sleep beforehand to make sure the grove is ready because the Atmega328 is reset in the previous step.

### CODE REVIEW

**Comment by DexterInd** [comment]
@CleoQc , thank you.  Can you put a line of documentation around that so that we don't delete it when we optimize it in 5 months?  :-)  #ruthlesscommenting

**Comment by CleoQc** [comment]
#bosshavinghisrevenge :)

**Comment by DexterInd** [comment]
:-)  I'm trying to be kind to the future @karan259 , future @CleoQc .

**Comment by CleoQc** [comment]
You're totally right. Thanks for calling me on it.

**Pull request merged**
