### PR TITLE
Install script moved back to older state to install avrdude normally

### PR DESCRIPTION
**Pull request by karan259**
…dude

### CODE REVIEW

**Comment by DexterInd** [comment]
Are we reverting back to the old version of avrdude?

**Comment by karan259** [comment]
The version is the same . 
For some reason this block is not working for a couple of people:
```
if [ ${PKG_RES} -eq -1 ]; then		
 -    cd /tmp		
 -    wget http://project-downloads.drogon.net/gertboard/${PKG_NAME}_${PKG_VER}_armhf.deb		
 -    sudo dpkg -i avrdude_5.10-4_armhf.deb		
 -    sudo chmod 4755 /usr/bin/avrdude		
 -fi
```
which does not install the avrdude with the Raspberry Pi GPIO programmer and breaking the firmware update. So this just goes back to the old method to make sure that it works .

**Comment by DexterInd** [comment]
Do we need to run an update on Raspbian for Robots as well?  Or is this just for folks that are running this independently of our OS?

**Comment by karan259** [comment]
We don't need to run it our image. GoPiGo and arduberry scripts install them in our image. This is mostly for people using their own image

**Pull request merged**
