### PR TITLE
add a new Flogo.io Activity for DigitalWrite

### PR DESCRIPTION
**Pull request by JGrotex**
here a new TIBCO Flogo.io Activity for DigitalWrite, will test and add others soon.
It can be used in any graphically defined flow definition and cross-compiled for Raspberry Pi.

happy IoT & regards, Jörg

### CODE REVIEW

**Comment by JGrotex** [comment]
just ignore my changes on the 'GO' Folder they are just for testing, just all new files in the 'flogo' Folder are related to this new Flogo.io IoT implementation.

thanks, Jörg

**Comment by RobertLucian** [comment]
Why close the PR @JGrotex ? Are you opening a separate one?

**Comment by JGrotex** [comment]
wanted to add some files, as the GO folder is really not working anymore with latest GO 1.9 found also some Issues with DHT read. Really like to replace this with newly tester Version.

**Comment by JGrotex** [comment]
created a new final pull request, looking forward hearing from you!
thanks, and regards, Jörg

Jörg Grote
www.Grote-Online.de

2018-03-22 16:39 GMT+01:00 Robert Lucian Chiriac <notifications@github.com>:

**Pull request closed without merging**
