### PR TITLE
Improved weather station

### PR DESCRIPTION
**Pull request by crazyquark**
Now with shutdown button and HTTP requests running on a second thread.

### CODE REVIEW

**Comment by crazyquark** [comment]
Please close this if you don't want it :)

**Comment by DexterInd** [comment]
Can you move the example to a new folder?  We need to keep the function of this really steady since it's cited in our instruction manuals.

**Comment by crazyquark** [comment]
Like outside Projects?

**Comment by DexterInd** [comment]
Yes, please.
John Cole
Founder, Dexter Industries

OUR PASSION IS ROBOTICS: We develop robotics for Raspberry Pi, LEGO®, 
and Arduino that are easy to use, fun, and have real-life applications 
for scientists and engineers . . . and those aspiring to be.
Website <http://www.dexterindustries.com/> | Blog 
<http://www.dexterindustries.com/site/?page_id=62> | Twitter 
<%0Ahttps://twitter.com/dexterind> | Facebook 
<https://www.facebook.com/dexterindustries>

**Comment by crazyquark** [comment]
OK, I will create a new pull request after re-organizing.

**Pull request closed without merging**
