### PR TITLE
Ensure GPS data is clean

### PR DESCRIPTION
**Pull request by CleoQc**
sometimes Latitude or Longitude coming in from the GPS are not pure floats
function cleanstr() ensures that no random characters can be found in them

added if __name__ == "__main__":  in case someone wants to pull in this file and benefit from the GPS class in their own code.

### CODE REVIEW

**Comment by DexterInd** [comment]
@CleoQc Did we document the proper port to put this in?

**Comment by CleoQc** [comment]
Now we did. :) 
Good catch!

**Comment by DexterInd** [comment]
Fabuoulullous!

**Comment by DexterInd** [comment]
Guess I'll go back and check the documentation on the other examples as well.

**Comment by CleoQc** [comment]
Oh I'm still working on cleaning this up.

**Pull request merged**
