### PR TITLE
Fix pi4 compatibility issues

### PR DESCRIPTION
**Pull request by Hansen0314**

### CODE REVIEW

**Comment by Pillar1989** [comment]
Why ？ @Hansen0314 Can you explain the principle?

**Comment by Hansen0314** [comment]
> Why ？ @Hansen0314 Can you explain the principle?
The pin of the Raspberry Pi 4 is low at default. Grove Pi+ cannot work fine if the gpio8 is low. we need to make the gpio8 on the raspberry PI4 to high.

**Comment by CleoQc** [comment]
What issues did you encounter with the GPIO8 being low?

**Comment by Hansen0314** [comment]
The pin of the Raspberry Pi 4 is low at default.

**Comment by CleoQc** [comment]
Can you describe an actual issue where this would make a difference?  Our grovepi is working fine as is. Is there a concrete use case where this shows up as a problem so I can add it to our test cases?

**Comment by Hansen0314** [comment]
I cannot work fine on raspberry pI4 by using GrovePi+ when I first use it. but it is working fine when I use the raspberry Pi3. I found that when we insert GrovePi + to Pi3, the RST LED on the board goes out and the board can work normally but When we insert GrovePi + to Pi4, the RST LED on the board is on, and GrovePi+ cannot work normally. then I find the RST LED indicate reset status at the mage328P of GrovePi+ .and the pin that can control the RST LED is GPIO8 on Raspberry Pi. So when we make the GPIO 8 of Pi4 to high that will off the RST LED make the mage328P of GrovePi+ go away reset status.

**Comment by CleoQc** [comment]
Can you tell us which version of the Pi4 you are using? I do not have the same issue here. 
The Pi4 has 3 versions out now, 1.1 and 1.2 (not the amount of memory, but changes to the board). 

See: https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

Run `cat /sys/firmware/devicetree/base/model`  to get the revision number.

**Comment by CleoQc** [comment]
Ok, I have a repro here finally if I use the September issue of Raspbian, but not with the February issue.

**Comment by Pillar1989** [comment]
@CleoQc We are currently using the older version of v1.1, and v1.2 should still be in the works.V1.2 only updates the power supply design of type-c.These IO voltages will not be affected.I suggest that you evaluate this PR as soon as possible. It is indeed a problem.

**Pull request merged**
