### PR TITLE
update setText_norefresh to fill remainder of display

### PR DESCRIPTION
**Pull request by Maosef**
setText_norefresh in the rgb_lcd now overwrites all previous text
previous changes reverted

### CODE REVIEW

**Comment by DexterInd** [comment]
@RobertLucian this looks pretty good to me, can you take a look?

**Comment by Maosef** [comment]
I rebased the changes and cleaned up the commit message.

**Comment by fhunleth** [comment]
Hi! Any updates on this issue? It would be great to get it merged.

**Comment by DexterInd** [comment]
@RobertLucian can you please review today?

**Comment by RobertLucian** [comment]
Yes I'm doing it now.

**Pull request merged**
