### PR TITLE
Add Ruby support

### PR DESCRIPTION
**Pull request by iia**
This PR adds support for using GrovePi with Ruby, [this is the related issue](https://github.com/DexterInd/GrovePi/issues/211).

This module depends on Ruby i2c-devices module.

Current State
==========
As the initial state of this module the following features are implemented and tested:

- Analog read on ports A0, A1 and A2.
- Analog write with PWM on ports D3, D5 and D6.
- Digital read/write on ports D2 through D8.
- Read/write data to I2C slave devices present on ports I2C-1, I2C-2 or I2C-3.
- Tested on Raspberry Pi 3, Model B and Raspberry Pi, Model B, Rev 2
  with Raspbian version: November 2017 and GrovePi+ with firmware version: 1.2.7.

Todo
====
- Implement rest of the commands that are supported by the firmware.
- Windows IoT core support.
- More testing.

### CODE REVIEW

**Comment by CleoQc** [comment]
Thanks for your contribution! I'm thrilled to see some Ruby love!

We'll test it soon, and then merge is accordingly. 

Thank you again.

**Comment by iia** [comment]
@RobertLucian You mean that currently there are three functions to read from ports **A0**, **A1** and **A2** namely, **read_analog_A0()**, **read_analog_A1()**, **read_analog_A2()** which are pretty much the same. Instead of these three function to have one function like **read_analog(<PORT>)** where the user will provide the intended port as the function argument and the same for the digital read/write functions ?

**Comment by RobertLucian** [comment]
Yeah, that's correct. And as for the function parameter, I think setting it as a string should do - that's how I see it. 
So, to confirm you, yes I'm thinking the function to be like `read_analog(<string port>)`.

**Comment by iia** [comment]
Wouldn't it be better to make the argument numeric? That way some validation can be provided easily and consistently compared to string comparison ?

**Comment by RobertLucian** [comment]
Well, it works both ways and I'm sure translating a number to a string (which string ought to be more descriptive than a simple numeric ID) isn't that hard in ruby. 
I don't have a strong opinion on it, so I think I can leave it to your best judgement.

**Comment by RobertLucian** [comment]
@iia I've tested it again and it seems to be all good. 
I'm merging this solution right now.

Also, the whole team of @DexterInd/sw-team thanks you for your contribution 👍 . 
Judging the README you wrote, I take that there are going to be future PRs, is that right?

**Comment by johnisanerd** [comment]
Hey @iia thank you again!  Great work and we really appreciate your contribution!

**Pull request merged**
