### PR TITLE
New grove devices

### PR DESCRIPTION
**Pull request by mercdev**

### CODE REVIEW

**Comment by mercdev** [comment]
Grove Water Atomization v1.0 Sensor
Grove Temperature & Humidity Sensor (SHT31)

**Comment by DexterInd** [comment]
Thanks for the PR!

**Comment by rickstoyroom** [comment]
OK so I got one of these but skipped the extra shield  -- hooked it up to my pi, set the gpio to high - worked, set the gpio to low, worked.. walked away.. came back set it to high again to test -- NOTHING and my pi disconnected me from ssh.. reconnect-  set gpio to low, commands came back fine.. set them to high.. disconnects and dumps me out of ssh..   whats going on?! hooked up to 5v, gnd, gpio 17 for white, and 22 for yellow

**Comment by rickstoyroom** [comment]
nvm I got it working
running the yellow wire to pin GPIO22 and setting low/high its working.. KABOOM

**Pull request merged**
