### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by alanch-ms**
Python3 compatibility:

- Add '()' to print statements
- Changed "except ErrorType, err:" => "except ErrorType as err:"
- Changed xrange() => range()
- Changed "<>" to "!="
- Changed "/" to "//" as appropriate for integer division
- Fixed tab vs spaces

### CODE REVIEW

**Comment by alanch-ms** [comment]
@karan259 - Here's some more changes for python 3.  I basically ran the tool '2to3' over the python scripts.  I only have included the changes that are compatible with both python 2.6+ and python 3.  Please do any testing as necessary.

There are some other differences that I didn't include in this pull request, such as python2's urllib2 vs python3's urllib.  You can see these differences by running the '2to3' tool again yourself.

**Comment by DexterInd** [comment]
@alanch-ms thanks for the pull request!  We're just taking a quick look over it, will merge shortly.

**Comment by DexterInd** [comment]
@karan259 can you take a quick look?  Just merged.

**Comment by karan259** [comment]
@alanch-ms - Thanks a lot for the pull. I have checked everything. There were a few small formatting changes which I have corrected and merged in the repo

**Pull request merged**
